name: Build dply docker image practicus

on:
  workflow_dispatch:

jobs:
  build-docker-dply-image-and-push:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Prepare docker build folder
      run: |
        mkdir ./docker
        cp ./Dockerfile-dply ./docker/Dockerfile
      shell: bash

    - name: Docker build image
      run: |
        cd ./docker
        docker image build -t ghcr.io/practicusai/practicus:22.11.0 -t ghcr.io/practicusai/practicus:latest .

    - name: Push image to GitHub Container Registry
      run: |
        docker push ghcr.io/practicusai/practicus --all-tags
